### PR TITLE
Show user info in rows in share dropdown

### PR DESCRIPTION
**Pull request by javfg**
This PR improves the info shown by the `AutocompleteItem` component:

* Details are shown in different rows instead of parenthesized in the same line.
* The share type will only show in non-user types.

Maybe we should also remove the username (or show it after the email)?

Before:
|User|Group|
|-|-|
|image|image|

After:
|User|Group|
|-|-|
|image|image|

### CODE REVIEW

**Comment by diocas** [comment]
In the groups, the email is a bit redundant since it doesn't give any special info, but for consistency I guess it's fine.

Can we decrease the size of the username and email?
And maybe put `<username or 'Group'> - <email>` in a single line?

If it's easy, the icon also has too much space on the left...

**Comment by javfg** [comment]
I can remove the email from groups easily, not completely sure about reducing font size:

|User|Group|
|-|-|
|image|image|


The horizontal padding comes from a variable `vs-dropdown-option-padding` which is set in `VueSelect`, the select component used by owncloud-design-system for their own `ocSelect`, I'm not sure we want to go down that path. :)

**Comment by diocas** [comment]
Please remove the `<>` from the email.
The font size difference seems a bit too big (but in the right direction). But, yea, we can keep the normal size for now.
But seems a bit less crowded, no?

For the padding, oh well, def not want to do changes in ods... Let's keep it as is for now. The icons are a bit too big as well.

**Comment by javfg** [comment]
I've made the font a bit bigger, removed the <> and hid the dash if there is no associated email for an user. Also, made icons a bit smaller (same size as the user avatar in the top bar).

image

**Comment by diocas** [comment]
Manually copied to my dev branch. Will push to cernbox soon.

**Pull request closed without merging**
